---
# tasks file for nfs-server

- name: Install nfs packages
  yum:
    name: nfs-utils
    state: present
  notify: Restart nfs

- name: Create nfs main directory
  file:
    path: "{{ item.path }}"
    state: directory
    owner: nfsnobody
    group: nfsnobody
    mode: 0755
  loop: "{{ nfs_exports }}"

- name: Gather service facts from the host
  service_facts:

- name: Check if firewalld package is installed
  yum:
    list: firewalld
  register: firewalld_package

- name: Allow nfs traffic on firewalld
  firewalld:
    service: nfs
    permanent: true
    state: enabled
  when: firewalld_package|json_query("results[?repo=='installed' && name == 'firewalld']")
  notify: Reload firewalld

- name: Add config file
  template:
    src: exports.j2
    dest: /etc/exports
  notify: Reaload exports

- name: Update cron jobs
  cron:
    name: "{{ item.1.job_name }}"
    day: "{{ item.1.day | default(omit) }}"
    hour: "{{ item.1.hour | default(0) }}"
    minute: "{{ item.1.minute | default(0) }}"
    month: "{{ item.1.month | default(omit) }}"
    weekday: "{{ item.1.weekday | default(omit) }}"
    job: "{{ item.1.command | default(omit) }}"
    user: "{{ item.1.user | default(omit) }}"
    state: "{{ item.1.state | default(omit) }}"
  loop: "{{ query('subelements', nfs_exports, 'cron_jobs', {'skip_missing': True}) }}"
