---
# handlers file for nfs-server

- name: Reload firewalld
  systemd:
    name: "firewalld"
    state: "reloaded"
    enabled: "yes"
  retries: 3
  when: not ansible_check_mode and ansible_facts.services['firewalld.service'].state == 'running'

- name: Restart nfs
  systemd:
    name: "nfs-server"
    state: "restarted"
    enabled: "yes"
  retries: 3
  when: not ansible_check_mode and ansible_facts.services is defined

- name: Reaload exports
  command: exportfs -ra